Repository ACCESS-NRI/access-om3-configs, pull requests merged in 2024-07, with the labels that each got.

#78 [0.25deg] Update MINIMUM_DEPTH & MASKING_DEPTH IN MOM_grid_init
  MOM_input
  docs/MOM_parameter_doc.all
Labels: in progress

#75 Meaningless values for {model_name}_cpl_dt in nuopc.runconfig
  nuopc.runconfig
Labels: in progress

#83 Update to latest ACCESS-OM3 executable: `025deg_jra55do_ryf`
  config.yaml
  manifests/exe.yaml
Labels: in progress

#82 Update to latest ACCESS-OM3 executable: `1deg_jra55do_iaf`
  config.yaml
  manifests/exe.yaml
Labels: in progress

#81 Update to latest ACCESS-OM3 executable: `1deg_jra55do_ryf`
  config.yaml
  manifests/exe.yaml
Labels: in progress

#85 Turn on AUTO_MASKTABLE
  MOM_input
  docs/MOM_parameter_doc.layout
Labels: mom6, om3-025, priority:high

#90 Add automatic cherry-pick workflow
  .github/workflows/automatic-cherry-pick.yaml
Labels: CI
